name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy frontend to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}

          script: |
            # Load NVM so node/npm/pm2 work
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            echo "Node version"
            node -v

            echo "NPM version"
            npm -v

            echo "Go to project folder"
            cd ~/deploy-frontend-aws

            echo "Pull latest code"
            git pull origin main

            echo "Install dependencies"
            npm ci

            echo "Build Next.js app"
            npm run build

            echo "Restart frontend app"

            if pm2 describe frontend > /dev/null
            then
              pm2 restart frontend
            else
              pm2 start npm --name "frontend" -- start
            fi

            pm2 save